[env:shipwrecked]
custom_meshtastic_hw_model = 0xFF
custom_meshtastic_hw_model_slug = SHIPWRECKED
custom_meshtastic_architecture = rp2040
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 0
custom_meshtastic_display_name = Shipwrecked Badge
custom_meshtastic_tags = Shipwrecked

extends = rp2040_base
board = rpipico
upload_protocol = picotool
build_flags =
  ${rp2040_base.build_flags}
  -D SHIPWRECKED
  -I variants/rp2040/shipwrecked
  -D DEBUG_RP2040_PORT=Serial
  -D EINK_DISPLAY_MODEL=GxEPD2_154_D67
  -D EINK_WIDTH=200
  -D EINK_HEIGHT=200
  -D EINK_NOT_HIBERNATE
  -D I2C_SDA=0
  -D I2C_SCL=1
lib_deps =
  ${rp2040_base.lib_deps}
  https://github.com/meshtastic/GxEPD2/archive/c7eb4c3c167cf396ef4f541cc5d4c6aa42f3c46b.zip
debug_build_flags = ${rp2040_base.build_flags}, -g
debug_tool = cmsis-dap
