name: Build badge firmware

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build
        run: pio run -e shipwrecked

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shipwrecked
          path: .pio/build/shipwrecked/*.uf2

      - name: Create release and upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: ${{ github.sha }}
          body: ${{ github.event.head_commit.message }}
          files: .pio/build/shipwrecked/firmware.uf2
